# In charts/retail-app-chart/templates/ingress.yaml

{{- if .Values.ingress.enabled -}}

apiVersion: networking.k8s.io/v1 # <-- THIS LINE MUST HAVE A BLANK LINE ABOVE IT
kind: Ingress
metadata:
  name: {{ include "retail-app-chart.fullname" . }}
  labels:
    {{- include "retail-app-chart.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - http:
        paths:
          - path: {{ .Values.ingress.path | quote }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "retail-app-chart.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
